### ISSUE TITLE
can u help with this

### ISSUE THREAD

**Issue by shadowdragon007** [kumarasinghe/linkedin-learning-downloader#2]
> linkedin-downloader@1.0.0 start C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master
> node index.js

You need to specify a valid "chromeExecutablePath" in config.js

**Comment by kumarasinghe** [comment]
Can you post your config.js file below?
You need to set the chrome.exe path in that.

**Comment by shadowdragon007** [comment]
my chrome browser address is C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
module.exports = {
    "chromeExecutablePath": "C:\Users\Dragoon\Downloads\Compressed\Bigasoft.Keygen\linkedin-learning-downloader-master\chromedriver.exe",
    "startPage": "https://www.linkedin.com/learning-login",
    "videoLoadWait": 4000
}

i tried using chrome browser address, but it didnt work

**Comment by kumarasinghe** [comment]
Try

`C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe`

**Comment by shadowdragon007** [comment]
thank you very much, it worked. 
can u please add the option of downloading videos into their subdirectory. currently, it just downloads and number videos randomly. 
update: the second course got downloaded according to the order in the course list.
